### PR TITLE
Add a more detailed README.md

### PR DESCRIPTION
**Pull request by 1Git2Clone**
# Content

I'm opening this PR early for any additional conversations or ideas related to the README.md file.

## Follow-up suggestions

A quick list of follow-up suggestions, will be updated as the conversation continues (if it doesn't get updated then mention me and/or read through the conversation).

1. We could also consider adding a CONTRIBUTORS.md file for any new contributors.

### CODE REVIEW

**Comment by izutsumifan** [comment]
This is good, thanks!

**Comment by 1Git2Clone** [comment]
> This is good, thanks!

Eh? There's a big TODO block in the README tho... You're welcome though! I'll work more on it later, have to do some errands for around 2 hours. In the meantime if you have any suggestions feel free to share them!

**Comment by izutsumifan** [comment]
All that really needs to be done is adding the contributors, but it really depends on what you'd define as a "contributor" to the mod - do you mean contributors to the repository or contributors to the modpack as a whole?

**Comment by izutsumifan** [comment]
> I'd say contributers as a whole but order them first as contributers to the repo and then just general contributors (or maybe split them as maintainers/contributors for more clarity).

Agreed.

**Comment by 1Git2Clone** [comment]
Alright, adding the CONTRIBUTORS.md file should be in a separate PR so I'll leave this PR like this. If you have any suggestions or corrections feel free to do them and/or say them here. I'll make sure to look into it!

**Pull request merged**
