### PR TITLE
change UTF8+BOM to UTF8 and CRLF to LF

### PR DESCRIPTION
**Pull request by eyalzus12**
how did the BOM even get there

might cause conflicts? git might be smart enough for this

### CODE REVIEW

**Comment by 1Git2Clone** [comment]
I don't know if I should merge this, it's causing a lot of merge conflicts and it's generally not a big deal, although I agree CRLF is a bit worse compared to LF in general.
You could try keeping UTF8+BOM and just change the line endings to see if there's no merge conflicts then I could merge that I suppose.

Also, it's not a bad idea to also add a .editorconfig like this one:

```txt
[*.cs]
end_of_line = lf
```

**Comment by eyalzus12** [comment]
alright. will do.

**Comment by eyalzus12** [comment]
the UTF8+BOM changes are minimal - just a change on the first line of the file (removing a char at the start)

the CRLF changes are the ones that cause conflicts, because they change every line

i'll add an .editorconfig entry

**Comment by eyalzus12** [comment]
done. do you want me to squash the first 3 commits?

**Comment by eyalzus12** [comment]
done. also updated `.csharpierrc.yaml` and run the formatting command.

might wanna add a git hook to automatically format when merging.

**Comment by 1Git2Clone** [comment]
> might wanna add a git hook to automatically format when merging.

You're right, I should see how to do that. Other than that, looks good to me!

**Pull request merged**
