### PR TITLE
Spirit DLL Added

### PR DESCRIPTION
**Pull request by DaChickenGamer**
Needed to use Thorium. Also made it so .idea is in the git ignore.

### CODE REVIEW

**Comment by DaChickenGamer** [comment]
> Let me know if there's a guarantee we can safely use the Thorium DLL. I could also try asking someone from the Thorium team about it.

Someone from the discord was asking the mod pack creator. I couldn't find a liscence preventing the use. It just says to ask for permission for cross compability, and you need a dll to do that. The way I got the DLL was by using a mod for extracting it. [image-4.png](https://github.com/user-attachments/assets/bf3cb2aa-5b02-463c-b65f-ec1b6d66aae7)

**Comment by 1Git2Clone** [comment]
> Someone from the discord was asking the mod pack creator.

I guess we'll just wait for their reply then. Make sure to ping me when it happens

**Review by 1Git2Clone — CHANGES_REQUESTED** [review]
Remove the Thorium DLL due to it being unapproved by the author.

**Comment by 1Git2Clone** [comment]
> [!IMPORTANT]
> Make sure to either override the entire commit history (in order to remove the Thorium Mod DLL) via force pushes on your fork or else it'll be a squash merge<sup>\[[1]\]</sup>.

[1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits "GitHub squash merge definition"

**Comment by DaChickenGamer** [comment]
Needed to update my main and it's these two mods are uncertain atm

**Pull request closed without merging**
